[package]
name = "radixsort-vulkan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = {version = "0.34.1", features=["macros"]}
vulkano-shaders = "0.34.0"
rand = "0.8.5"